# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields
import mezzanine.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20170411_0504'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('cover_pix', models.ImageField(upload_to='nrsa_pages')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='NRSANewsEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('edit_as_html', models.BooleanField(default=False)),
                ('feature_pictured', models.ImageField(blank=True, null=True, upload_to='news_event')),
                ('featured', models.BooleanField(default=False)),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
            ],
            options={
                'verbose_name': 'News event',
                'verbose_name_plural': 'News events',
                'ordering': ('-publish_date',),
            },
            bases=('pages.page', models.Model, mezzanine.utils.models.AdminThumbMixin),
        ),
        migrations.CreateModel(
            name='NRSANewsEventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='NRSAPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('edit_as_html', models.BooleanField(default=False)),
                ('cover_pix', models.ImageField(upload_to='nrsa_pages')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.AddField(
            model_name='nrsanewsevent',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='news_events', to='mToM.NRSANewsEventCategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='nrsanewsevent',
            name='related_news',
            field=models.ManyToManyField(blank=True, related_name='_nrsanewsevent_related_news_+', to='mToM.NRSANewsEvent', verbose_name='Related news'),
        ),
    ]
